In [ ]:
import pandas as pd

df = pd.read_csv("quotes_dataset_100.csv")

df.head()

,Quote,Author,Tags
0,“The world as we have created it is a process ...,Albert Einstein,"change, deep-thoughts, thinking, world"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"abilities, choices"
2,“There are only two ways to live your life. On...,Albert Einstein,"inspirational, life, live, miracle, miracles"
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"aliteracy, books, classic, humor"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"be-yourself, inspirational"

In [ ]:
print("Shape:", df.shape)

df.info()

Shape: (100, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Quote   100 non-null    object
 1   Author  100 non-null    object
 2   Tags    97 non-null     object
dtypes: object(3)
memory usage: 2.5+ KB

In [ ]:
df.isnull().sum()

Quote     0
Author    0
Tags      3
dtype: int64

In [ ]:
df.describe(include='all')

,Quote,Author,Tags
count,100,100,97
unique,100,50,83
top,“The world as we have created it is a process ...,Albert Einstein,love
freq,1,10,4

In [ ]:
df['Author'].value_counts().head(10)

Author
Albert Einstein      10
J.K. Rowling          9
Marilyn Monroe        7
Dr. Seuss             6
Mark Twain            6
Jane Austen           5
C.S. Lewis            5
Bob Marley            3
Mother Teresa         2
Eleanor Roosevelt     2
Name: count, dtype: int64

In [ ]:
df['Quote_Length'] = df['Quote'].apply(len)

df.head()

,Quote,Author,Tags,Quote_Length
0,“The world as we have created it is a process ...,Albert Einstein,"change, deep-thoughts, thinking, world",115
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"abilities, choices",85
2,“There are only two ways to live your life. On...,Albert Einstein,"inspirational, life, live, miracle, miracles",131
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"aliteracy, books, classic, humor",104
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"be-yourself, inspirational",111

In [ ]:
print("Average Quote Length:", df['Quote_Length'].mean())

print("Longest Quote Length:", df['Quote_Length'].max())

print("Shortest Quote Length:", df['Quote_Length'].min())

Average Quote Length: 122.27
Longest Quote Length: 1084
Shortest Quote Length: 34

In [ ]:
df.sort_values(by='Quote_Length', ascending=False)[['Author','Quote_Length']].head()

            Author  Quote_Length
10  Marilyn Monroe          1084
13      Bob Marley           697
63      C.S. Lewis           516
20    Pablo Neruda           319
84     Jane Austen           309